config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  root 'home#index'

  get 'home/compare_pictures/:id' => 'home#compare_pictures', as: :compare_pictures
  get 'home/save_result/:better_id/:group_id/:project_id' => 'home#save_result', as: :save_result
  get 'home/add_pictures' => 'home#add_pictures', as: :add_pictures
  post 'home/save_pictures' => 'home#save_pictures', as: :save_pictures

  get 'home/new_project' => 'home#new_project', as: :new_project
  get 'home/edit_project' => 'home#edit_project', as: :edit_project

  post 'home/create_project' => 'home#create_project', as: :create_project
  post 'home/update_project' => 'home#update_project', as: :update_project

  get 'home/random_pictures' => 'home#random_pictures', as: :random_pictures
  get 'home/save_random_result/:better_id/:group_id' => 'home#save_random_result', as: :save_random_result

  scope module: 'api' do
    get 'api/home/project_results/:project_id' => 'home#project_results', as: :api_project_results
    post 'api/home/create_project' => 'home#create_project', as: :api_create_project
    post 'api/home/add_pictures_to_project/:project_id' => 'home#add_pictures_to_project', as: :api_add_pictures
  end

end

app/controllers/api/home_controller.rb
require 'csv'
class Api::HomeController < Api::ApiController
  include HomeHelper
  before_action :authenticate_request

  def index
    render text: request.inspect
  end

  def project_results
    @project = Project.find(params[:project_id])
    results = CSV.generate do |csv|
      @project.picture_groups.where(marked:true).each do |picture_group|
        row = [picture_group.better.url]
        # this loop is used because picture_group.pluck(:url).join(',') puts an extra " at the end and beginning.
        picture_group.pictures.each do |picture|
          row.push picture.url
        end
        csv << row
      end
    end
    render text: results
  end

  def create_project
    if params[:urls].present? and params[:groups].present?
      @project = Project.new(title: params[:title], description: params[:description])
      @project = add_pictures(@project)
      render json: @project, include: :picture_groups
    else
      render text: 'Un Matched Params', status: 400
    end

  end

  def add_pictures_to_project
    if params[:project_id].present? and params[:urls].present? and params[:groups].present?
      @project = Project.find(params[:project_id])
      @project = add_pictures(@project)
      render json: @project, include: :picture_groups
    else

    end
  end

  def add_pictures(project)
    urls = params[:urls]
    groups = params[:groups]
    urls = urls.split(',')
    picture_groups = create_pictures_and_groups urls, groups
    project.picture_groups << picture_groups if picture_groups.present?
    project.save
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HomeHelper
  include ActionView::Helpers::NumberHelper

  before_action :authenticate_user!, except: [:compare_pictures, :index, :save_result]
  def index
    @projects = Project.all
  end

  def compare_pictures
    @project = Project.find(params[:id])
    @picture_group = @project.picture_groups.where(marked: false).try(:first)
    redirect_to random_pictures_path if @picture_group.nil?
    @progress = (@project.picture_groups.where(marked: true).length.to_f / @project.picture_groups.length.to_f) * 100.0
    @progress = number_to_human @progress
  end

  def save_result
    @better = Picture.find(params[:better_id]) if params[:better_id].present?
    @picture_group = PictureGroup.find(params[:group_id]) if params[:group_id].present?
    @picture_group.update better_id: @better.id, marked:true if @picture_group.present?
    respond_to do |format|
      format.html { redirect_to compare_pictures_path(params[:project_id]) }
      format.js do
        @project = Project.find(params[:project_id])
            render json:  {project_id: @project.id, action_name: 'compare_pictures'}
      end
    end
  end

  def random_pictures
    @picture_group = PictureGroup.where(marked: false, project: nil).try :first
    puts @picture_group.inspect
  end

  def save_random_result
    @better = Picture.find(params[:better_id]) if params[:better_id].present?
    @picture_group = PictureGroup.find(params[:group_id]) if params[:group_id].present?
    @picture_group.update better_id: @better.id, marked: true if @picture_group.present?
    puts @picture_group.inspect
    respond_to do |format|
      format.html { redirect_to random_pictures_path(params[:project_id]) }
      format.js do
        render json:  {action_name: 'random_pictures'}
      end
    end
  end

  def add_pictures
    @picture = Picture.new
  end

  def save_pictures
    urls = params[:urls].split(',') unless params[:urls].nil?
    groups = params[:groups] unless params[:groups].nil?
    create_pictures_and_groups urls, groups
    redirect_to random_pictures_path
  end

  def new_project
    @project = Project.new
  end

  def edit_project
    @project = Project.find(params[:id])
  end

  def create_project
    @project = Project.new(project_params)
    urls = params[:urls].split(',') unless params[:urls].nil?
    groups = params[:groups] unless params[:groups].nil?
    @picture_groups = create_pictures_and_groups urls, groups
    @project.picture_groups << @picture_groups if @picture_groups.present?
    @project.save
    redirect_to compare_pictures_path(@project.id)
  end

  def update_project

  end

  private
  def project_params
    params.require(:project).permit(:title, :description)
  end

end

app/helpers/home_helper.rb
module HomeHelper
  def create_pictures_and_groups(urls, groups)
    urls.each do |url|
      Picture.create(url: url)
    end
    picture_groups = []
    groups = groups.split('][')
    groups.each do |group|
      @picture_group = PictureGroup.new marked: false
      group.split(',').each do |index_of_url|
        index_of_url = index_of_url.delete('[').delete(']').to_i
        @picture_group.pictures << Picture.find_by_url(urls[index_of_url - 1]) if urls[index_of_url - 1].present?
      end
      @picture_group.save if @picture_group.pictures.present?
      picture_groups << @picture_group if @picture_group.present?
    end
    picture_groups
  end
end

app/views/home/_compare_pictures.html.erb
<% picture_group.pictures.each do |picture| %>
    <div class="col-sm-6 col-xs-6" >
      <div class="col-sm-12 col-xs-12">
        <img class="img-responsive image" src="<%= picture.url %>"/>
      </div>
      <div class="button-row col-sm-12 col-xs-12 centered">
        <% if picture_group.project.present? %>
            <a href="<%= save_result_path(picture.id, picture_group.id, picture_group.project.id) %>" role="button" class="btn btn-lg choose-button">Choose</a>
        <% else %>
            <a href="<%= save_random_result_path(picture.id, picture_group.id) %>" role="button" class="btn btn-lg choose-button">Choose</a>
        <% end  %>
      </div>
    </div>
<% end %>

app/views/home/_project_form.html.erb
<div class="container centered-box project-form">
  <% @form_label = @project.new_record? ? :create_project : :update_project %>
  <div>
    <h2 class="form-heading"><%= @form_label.to_s.titleize %></h2>
  </div>
  <div class="col-sm-12">
    <%= simple_form_for(@project, url: {action: @form_label }, html: { class: 'form-horizontal' } ) do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs col-sm-12 auto-margin">
          <%= f.input :title %>
          <%= f.input :description, input_html: {rows: 3, style: 'resize:none' } %>
        </div>

        <div class="input-group col-sm-12 auto-margin">
          <label for="urls">URLs</label>
          <textarea name="urls" class="form-control url_file_input" rows="3" style="resize: none" id="urls"> </textarea>
        </div>
        <br>

        <div class="input-group col-sm-12 auto-margin">
          <label for="groups">Groups</label>
          <textarea name="groups" class="form-control url_file_input" rows="3" style="resize: none" id="groups"> </textarea>
        </div>

        <div class="form-actions">
          <%= f.button :submit, label: @project.new_record? ? 'Create' : 'Edit', class: 'button-row col-sm-12 large-submit btn btn-lg'%>
        </div>

    <% end %>
  </div>
</div>

app/views/home/add_pictures.html.erb
<div class="container centered-box login-form">
  <div>
    <h2 class="form-heading">Add Images</h2>
  </div>
  <div class="col-sm-12">
  <%= form_tag( save_pictures_path , {class: 'form-horizontal', method: 'post'}) do %>
    <!--<div class="form-group">-->
      <!--<label for="url_file" class="col-sm-3 control-label">URLs</label>-->
      <!--<div class="col-sm-7 file">-->
        <!--<input type="file" name="file_with_urls" id="url_file">-->
      <!--</divmultipart: true>-->
    <!--</div>-->
    <!--<div class="form-group">-->
      <!--<label for="pair_file" class="col-sm-3 control-label">Pairs</label>-->
      <!--<div class="col-sm-7 file">-->
        <!--<input type="file" name="file_with_pairs" id="pair_file">-->
      <!--</div>-->
    <!--</div>-->

    <div class="input-group col-sm-12 auto-margin">
      <label for="urls">URLs</label>
      <textarea name="urls" class="form-control url_file_input" rows="3" style="resize: none" id="urls"> </textarea>
    </div>
    <br>

    <div class="input-group col-sm-12 auto-margin">
    <label for="groups">Groups</label>
    <textarea name="groups" class="form-control url_file_input" rows="3" style="resize: none" id="groups"> </textarea>
    </div>

    <button type="submit" class="button-row col-sm-12 large-submit btn btn-lg">Submit</button>
  <% end %>
  </div>
</div>

app/views/home/compare_pictures.html.erb
<div class="row" id="notice"><%= flash[:notice] %></div>
<% if @project.picture_groups.nil? %>
    <div class="row">Sorry, We Don't Have Any Pictures In This Project. Please Select Another.</div>
<% elsif @project.picture_groups.where(marked: false).empty? %>
    <div class="row">This Project is Completed.Please Select Another.</div>
<% else %>
  <div class="row">
    <%= render partial: 'compare_pictures', locals: {picture_group: @picture_group } %>
    <div class="col-sm-12">
      <div class="progress">
        <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="<%= @progress %>" aria-valuemin="0" aria-valuemax="100" style="width:<%= @progress %>%"><%= "#{@progress}% Completed" %></div>
      </div>
    </div>
  </div>
<% end %>

app/views/home/edit_project.html.erb
<%= render 'project_form' %>

app/views/home/index.html.erb
<div class="row" id="notice"><%= flash[:notice] %></div>
<% if @projects.nil? || @projects.empty? %>
    <div class="row">Sorry, We don't have any projects going on. <%= link_to 'Create New', new_project_path, {class: 'light-purple'} %></div>
<% else %>
    <div class="row">
      <% @projects.each do |project| %>
        <div class="panel panel-default project-box">
          <div class="panel-heading project-heading">
            <h3 class="panel-title">
              <% if project.picture_groups.where(marked: false).empty? %>
                  <%= link_to "#{project.title} #{'- Completed' }", action: :compare_pictures, id: project.id  %>
              <% elsif project.picture_groups.where(marked: true).empty? %>
                  <%= link_to "#{project.title} #{'- New' }", action: :compare_pictures, id: project.id  %>
              <% else %>
                  <%= link_to "#{project.title} #{'- In Progress'}", action: :compare_pictures, id: project.id %>
              <% end %>

            </h3>
          </div>
          <div class="panel-body project" style="color: #999999">
            <div class="col-sm-12 project">
                <% project.picture_groups.each_with_index do |group, index| %>
                  <% if index < 2  %>
                  <div class="col-sm-6 group">
                    <% group.pictures.each_with_index do |picture, index| %>
                        <% if index < 2   %>
                            <div class="col-sm-6"><a class="thumbnail"><img class="picture" src="<%= picture.url %>"/></a></div>
                        <% end %>
                    <% end  %>
                  </div>
                  <% end  %>
                <% end  %>
            </div>
          </div>
        </div>
      <% end  %>
    </div>
<% end %>

app/views/home/new_project.html.erb
<%= render 'project_form' %>

app/views/home/random_pictures.html.erb
<div class="row" id="notice"><%= flash[:notice] %></div>
<% if @picture_group.present? %>
    <div class="row">
      <%= render partial: 'compare_pictures', locals: {picture_group: @picture_group } %>
    </div>
<% else %>
    <div class="row">Sorry, We Don't Have Any Pictures Right Now. Please Come Back Later.</div>
<% end %>