config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  root 'home#index'

  get 'home/compare_pictures/:id' => 'home#compare_pictures', as: :compare_pictures
  get 'home/save_result/:better_id/:group_id/:project_id' => 'home#save_result', as: :save_result
  get 'home/add_pictures' => 'home#add_pictures', as: :add_pictures
  post 'home/save_pictures' => 'home#save_pictures', as: :save_pictures

  get 'home/new_project' => 'home#new_project', as: :new_project
  get 'home/edit_project' => 'home#edit_project', as: :edit_project

  post 'home/create_project' => 'home#create_project', as: :create_project
  post 'home/update_project' => 'home#update_project', as: :update_project

  get 'home/random_pictures' => 'home#random_pictures', as: :random_pictures
  get 'home/save_random_result/:better_id/:group_id' => 'home#save_random_result', as: :save_random_result

  scope module: 'api' do
    get 'api/home/project_results/:project_id' => 'home#project_results', as: :api_project_results
    post 'api/home/create_project' => 'home#create_project', as: :api_create_project
    post 'api/home/add_pictures_to_project/:project_id' => 'home#add_pictures_to_project', as: :api_add_pictures
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HotOrNot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <!-- Header -->
    <nav class="navbar navbar-default" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">HotOrNot</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="<%= add_pictures_path %>">Add Images</a></li>
          <li><a href="<%= new_project_path %>">Create Project</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <% if current_user.present? %>
                <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
            <% else  %>
                <%= link_to 'Login', new_user_session_path %>
            <% end  %>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
    <!-- Header Closed -->

    <!-- Main Container -->
    <div class="container main-container">
        <%= yield %>
    </div>
    <!-- Main Container Closed-->
</body>
</html>